name: Push docker image
on:
  release:
    types: 
      - published
jobs:
  Test_Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: get docker_tag repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/docker_tag
    - name: test docker image
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
        repository: moleszek/vagrant
        tag_latest: false
        push: false
        github: true
        token: ${{ secrets.token }}
        owner: ${{ github.repository_owner }}
  Push_Image:
    needs: Test_Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: get docker_tag repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/docker_tag
    - name: push docker image to Docker Hub
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
        repository: moleszek/vagrant
        tag_latest: false
        push: true
        github: true
        token: ${{ secrets.token }}
        owner: ${{ github.repository_owner }}
    - name: update Docker README
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.docker_username }}
        DOCKERHUB_PASSWORD: ${{ secrets.docker_password }}
        DOCKERHUB_REPOSITORY: moleszek/vagrant
        README_FILEPATH: README.md