name: Push docker image to DockerHub
on:
  release:
    types: 
      - published
jobs:
  #build_docker_image:
  #    runs-on: ubuntu-latest
  #    container: docker:stable
  #    steps:
  #    - name: Checkout docker_terraform repository
  #      uses: actions/checkout@v2
  #      with:
  #        repository: ${{ github.repository }}
  #        ref: main
  #        token: ${{ secrets.token }}
  #    - name: Build dockerfile
  #      run: docker build -t docker-vagrant .
  test_docker_vagrant_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout docker_vagrant repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main
        token: ${{ secrets.token }}
    - name: Get terraform version
      id: version
      run: |
        check=$(curl -s "$url/hashicorp/$component/tags" | grep '"name":' | sed "s/[^0-9.]//g" | head -n1)
        ::set-output name=response::$check
    - name: Set name
      run: terraform:${{ steps.version.outputs.response }}
    #- name: Checkout docker_tag repository
    #  uses: actions/checkout@v2
    #  with:
    #    repository: ${{ github.repository_owner }}/docker_tag
    #    ref: master
    #    token: ${{ secrets.token }}
    #    path: .github/actions/docker_tag
    #- name: Test docker image
    #  uses: ./.github/actions/docker_tag
    #  with:
    #    username: ${{ secrets.docker_username }}
    #    password: ${{ secrets.docker_token }}
    #    repository: moleszek/vagrant
    #    tag_latest: false
    #    push: false
    #    github: true
    #    token: ${{ secrets.token }}
    #    owner: ${{ github.repository_owner }}
  #push_docker_image_to_dockerhub:
  #  needs:
  #    - build_docker_image
  #    - test_docker_vagrant_version
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Checkout docker_vagrant repository
  #    uses: actions/checkout@v2
  #    with:
  #      repository: ${{ github.repository }}
  #      ref: main
  #      token: ${{ secrets.token }}
    #- name: Checkout docker_tag repository
    #  uses: actions/checkout@v2
    #  with:
    #    repository: ${{ github.repository_owner }}/docker_tag
    #    ref: master
    #    token: ${{ secrets.token }}
    #    path: .github/actions/docker_tag
    #- name: Push docker image to Docker Hub
    #  uses: ./.github/actions/docker_tag
    #  with:
    #    username: ${{ secrets.docker_username }}
    #    password: ${{ secrets.docker_token }}
    #    repository: moleszek/vagrant
    #    tag_latest: false
    #    push: true
    #    github: true
    #    token: ${{ secrets.token }}
    #    owner: ${{ github.repository_owner }}
    #- name: update Docker README
    #  uses: peter-evans/dockerhub-description@v2.1.0
    #  env:
    #    DOCKERHUB_USERNAME: ${{ secrets.docker_username }}
    #    DOCKERHUB_PASSWORD: ${{ secrets.docker_password }}
    #    DOCKERHUB_REPOSITORY: moleszek/vagrant
    #    README_FILEPATH: README.md