name: Docker registry
on:
  release:
    types: 
      - published
jobs:
  build_docker_image:
      runs-on: ubuntu-latest
      container: docker:stable
      steps:
      - name: Checkout docker_terraform repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          token: ${{ secrets.token }}
      - name: Build dockerfile
        run: docker build -t docker-vagrant .
  push_docker_image_to_dockerhub:
    needs:
      - build_docker_image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main
        token: ${{ secrets.token }}
    - name: Check Vagrant version
      id: version
      run: |
        check=$(curl -s "https://api.github.com/repos/hashicorp/vagrant/tags" | grep '"name":' | sed "s/[^0-9.]//g" | head -n1)
        echo ::set-output name=response::$check
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        tags: moleszek/vagrant:${{ steps.version.outputs.response }}
    #- name: update Docker README
    #  uses: peter-evans/dockerhub-description@v2.1.0
    #  env:
    #    DOCKERHUB_USERNAME: ${{ secrets.docker_username }}
    #    DOCKERHUB_PASSWORD: ${{ secrets.docker_password }}
    #    DOCKERHUB_REPOSITORY: moleszek/vagrant
    #    README_FILEPATH: README.md