name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"
jobs:
  test_docker_image:
    runs-on: ubuntu-latest
    container: docker:stable
    steps:
    - name: Checkout pihole repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        token: ${{ secrets.token }}
    - name: Build dockerfile
      run: docker build -t vagrant -f Docker/Dockerfile .
